server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/<github-username>/app-config.git
          uri: https://github.com/pprabhakaran-sol/apps-spring-cloud-services-labs.git
